// INTERRUPT
#define FLOW_SENSOR PD2 //D2
// PWM
#define PUMP_RELAY PB3 //D11
#define THERMOBLOCK_RELAY PB2 //D12
// ANALOG
#define PRESSURE_SENSOR A7
#define TEMPERATURE_SENSOR A6
//#define TEMPERATURE_SENSOR_SUPPORT PC5